
services:
  # RabbitMQ Message Broker
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"     # AMQP port
      - "15672:15672"   # Management UI
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin123
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - microservices-network

  # CockroachDB Database for Auth Service
  cockroachdb-auth:
    image: cockroachdb/cockroach:latest
    container_name: cockroachdb-auth
    command: start-single-node --insecure
    ports:
      - "26257:26257"   # SQL port
      - "8080:8080"     # Admin UI
    volumes:
      - cockroachdb_auth_data:/cockroach/cockroach-data
    environment:
      - COCKROACH_DATABASE=auth_db
    networks:
      - microservices-network

  # CockroachDB Database for Publications Service
  cockroachdb-publications:
    image: cockroachdb/cockroach:latest
    container_name: cockroachdb-publications
    command: start-single-node --insecure
    ports:
      - "26258:26257"   # SQL port
      - "8081:8080"     # Admin UI
    volumes:
      - cockroachdb_publications_data:/cockroach/cockroach-data
    environment:
      - COCKROACH_DATABASE=publications_db
    networks:
      - microservices-network

  # CockroachDB Database for Catalog Service
  cockroachdb-catalog:
    image: cockroachdb/cockroach:latest
    container_name: cockroachdb-catalog
    command: start-single-node --insecure
    ports:
      - "26259:26257"   # SQL port
      - "8082:8080"     # Admin UI
    volumes:
      - cockroachdb_catalog_data:/cockroach/cockroach-data
    environment:
      - COCKROACH_DATABASE=catalog_db
    networks:
      - microservices-network

  # CockroachDB Database for Notifications Service
  cockroachdb-notifications:
    image: cockroachdb/cockroach:latest
    container_name: cockroachdb-notifications
    command: start-single-node --insecure
    ports:
      - "26260:26257"   # SQL port
      - "8083:8080"     # Admin UI
    volumes:
      - cockroachdb_notifications_data:/cockroach/cockroach-data
    environment:
      - COCKROACH_DATABASE=notifications_db
    networks:
      - microservices-network

  # Consul Service Discovery
  consul:
    image: hashicorp/consul:latest
    container_name: consul
    ports:
      - "8500:8500"     # HTTP API
      - "8600:8600/udp" # DNS
    command: agent -server -ui -node=server-1 -bootstrap-expect=1 -client=0.0.0.0
    networks:
      - microservices-network

volumes:
  rabbitmq_data:
  cockroachdb_auth_data:
  cockroachdb_publications_data:
  cockroachdb_catalog_data:
  cockroachdb_notifications_data:

networks:
  microservices-network:
    driver: bridge 