server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  # Docker container logs
  - job_name: docker
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 5s
        filters:
          - name: label
            values: ["logging=promtail"]
    relabel_configs:
      - source_labels: ['__meta_docker_container_name']
        regex: '/(.*)'
        target_label: 'container'
      - source_labels: ['__meta_docker_container_log_stream']
        target_label: 'logstream'
      - source_labels: ['__meta_docker_container_label_logging_job_name']
        target_label: 'job'

  # Microservices logs
  - job_name: microservices
    static_configs:
      - targets:
          - localhost
        labels:
          job: microservices
          __path__: /var/log/microservices/*.log
    pipeline_stages:
      - json:
          expressions:
            level: level
            service: service
            timestamp: timestamp
            message: message
            traceId: traceId
            correlationId: correlationId
            component: component
      - labels:
          level:
          service:
          component:
          traceId:
          correlationId:
      - timestamp:
          source: timestamp
          format: RFC3339Nano
      - output:
          source: message

  # System logs
  - job_name: syslog
    static_configs:
      - targets:
          - localhost
        labels:
          job: syslog
          __path__: /var/log/syslog
    pipeline_stages:
      - regex:
          expression: '^(?P<timestamp>\w+ \d+ \d+:\d+:\d+) (?P<hostname>\w+) (?P<service>\w+)\[(?P<pid>\d+)\]: (?P<message>.*)$'
      - labels:
          service:
          hostname:
      - timestamp:
          source: timestamp
          format: Jan 02 15:04:05

  # Application specific logs
  - job_name: gateway-service
    static_configs:
      - targets:
          - localhost
        labels:
          job: gateway-service
          service: api-gateway
          __path__: /var/log/microservices/gateway-service.log
    pipeline_stages:
      - json:
          expressions:
            level: level
            timestamp: timestamp
            message: message
            traceId: traceId
            correlationId: correlationId
            operation: metadata.operation
            httpMethod: metadata.httpMethod
            httpStatusCode: metadata.httpStatusCode
            responseTime: metadata.responseTime
      - labels:
          level:
          operation:
          httpMethod:
          httpStatusCode:
      - timestamp:
          source: timestamp
          format: RFC3339Nano

  - job_name: auth-service
    static_configs:
      - targets:
          - localhost
        labels:
          job: auth-service
          service: auth-service
          __path__: /var/log/microservices/auth-service.log
    pipeline_stages:
      - json:
          expressions:
            level: level
            timestamp: timestamp
            message: message
            traceId: traceId
            userId: userId
            operation: metadata.operation
      - labels:
          level:
          operation:
      - timestamp:
          source: timestamp
          format: RFC3339Nano

  - job_name: publications-service
    static_configs:
      - targets:
          - localhost
        labels:
          job: publications-service
          service: publications-service
          __path__: /var/log/microservices/publications-service.log
    pipeline_stages:
      - json:
          expressions:
            level: level
            timestamp: timestamp
            message: message
            traceId: traceId
            operation: metadata.operation
      - labels:
          level:
          operation:
      - timestamp:
          source: timestamp
          format: RFC3339Nano

  - job_name: catalog-service
    static_configs:
      - targets:
          - localhost
        labels:
          job: catalog-service
          service: catalog-service
          __path__: /var/log/microservices/catalog-service.log
    pipeline_stages:
      - json:
          expressions:
            level: level
            timestamp: timestamp
            message: message
            traceId: traceId
            operation: metadata.operation
      - labels:
          level:
          operation:
      - timestamp:
          source: timestamp
          format: RFC3339Nano

  - job_name: notifications-service
    static_configs:
      - targets:
          - localhost
        labels:
          job: notifications-service
          service: notifications-service
          __path__: /var/log/microservices/notifications-service.log
    pipeline_stages:
      - json:
          expressions:
            level: level
            timestamp: timestamp
            message: message
            traceId: traceId
            operation: metadata.operation
      - labels:
          level:
          operation:
      - timestamp:
          source: timestamp
          format: RFC3339Nano